#include "TPoint.h"

TV_BOILERPLATE_FUNCTIONS(TPoint)
TV_BINARY_OPERATOR_COPYABLE_OBJECT(TPoint, TPoint, +, add, TPoint)
TV_BINARY_OPERATOR_COPYABLE_OBJECT(TPoint, TPoint, -, subtract, TPoint)
TV_BINARY_OPERATOR_IN_PLACE(TPoint, TPoint, +, add)
TV_BINARY_OPERATOR_IN_PLACE(TPoint, TPoint, -, subtract)
TV_GET_SET_PRIMITIVE(TPoint, int32_t, x)
TV_GET_SET_PRIMITIVE(TPoint, int32_t, y)
